kind: pipeline
name: default

clone:
  disable: true

steps:
- name: update_ci
  image: docker:git
  environment:
    POMPA_CI_DEPLOY_KEY:
      from_secret: pompa_ci_deploy_key
  commands:
  - mkdir -p ~/.ssh
  - echo -ne "$POMPA_CI_DEPLOY_KEY" > ~/.ssh/id_rsa
  - ssh-keyscan -H github.com > ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/id_rsa ~/.ssh/known_hosts
  - git clone git@github.com:m1nl/pompa-ci.git
  - cd pompa-ci
  - git config user.email "drone@nalewajski.pl"
  - git config user.name "Drone CI"
  - git config merge.ours.driver true
  - git remote add upstream https://github.com/m1nl/pompa-docker.git
  - git fetch upstream
  - git checkout --theirs upstream/master -- web/pompa
  - git checkout --theirs upstream/master -- app/pompa-api
  - git commit --allow-empty -m "merge with $DRONE_COMMIT ($DRONE_COMMIT_MESSAGE) by $DRONE_COMMIT_AUTHOR"
  - git merge --squash --allow-unrelated-histories --strategy=recursive --strategy-option=theirs upstream/master
  - git commit --allow-empty --amend --no-edit
  - git push origin master
