kind: pipeline
name: default

clone:
  disable: true

steps:
- name: update_ci
  image: docker:git
  commands:
  - git clone https://github.com/m1nl/pompa-ci.git
  - cd pompa-ci
  - git config user.email "drone@nalewajski.pl"
  - git config user.name "Drone CI"
  - git config merge.ours.driver true
  - git config merge.theirs.driver true
  - git remote add upstream https://github.com/m1nl/pompa-docker.git
  - git fetch upstream
  - git merge --squash --allow-unrelated-histories upstream/master
  - git commit --allow-empty -m "merge with $DRONE_COMMIT ($DRONE_COMMIT_MESSAGE) by $DRONE_COMMIT_AUTHOR"
  - git push origin master
