default: &default
  adapter: postgresql
  database: <%= ENV['POMPA_DB'] %>
  username: <%= ENV['POMPA_DB_USERNAME'] %>
  password: <%= File.read('/run/secrets/pompa_db_password') %>
  host: <%= ENV['POMPA_DB_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
