redis_default: &redis_default
  driver: hiredis
  pool_size: 15
  url: "redis://redis"
  db: 0

default: &default
  endpoints:
    admin: true
    public: true
    sidekiq_console: true
  template:
    base_url: "<%= ENV['POMPA_BASE_URL'] || 'http://localhost:8081' %>"
  redis:
    <<: *redis_default

production:
  <<: *default
  redis:
    <<: *redis_default
    db: 1
    pool_size: 25

development:
  <<: *default
  log_level: "debug"

test:
  <<: *default
